server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:digital_waiter_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: dw

redis:
  cart:
    ttl-hours: ${REDIS_CART_TTL:2}
  menu:
    ttl-hours: ${REDIS_MENU_TTL:1}

iiko:
  url: https://api-ru.iiko.services
  operation:
    status-check:
      max-attempts: ${IIKO_STATUS_CHECK_MAX_ATTEMPTS:5}
      delay-ms: ${IIKO_STATUS_CHECK_DELAY_MS:500}

digital-waiter:
  url: https://digital-waiter.sberlab.nsu.ru

local:
  url: http://localhost:8081

token:
  signing:
    key: ${TOKEN_AUTH_KEY:mZ2V3aXJ0aGZ4c2xqZG5mbXlza2Zqd2Vya2FzbGpoZWQ0MTI=}
  duration:
    access: ${TOKEN_DURATION_ACCESS:60}
    update: ${TOKEN_DURATION_UPDATE:1440}

crypto:
  api-key:
    secret: ${API_KEY_CRYPTO_SECRET:Cu7xiXD0bUK/j3NvEEo5/ZbxhwxTFeUEvTewAKv6LCo=}
