server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/digital_waiter_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  flyway:
    enabled: true
    locations: classpath:db/migration

redis:
  cart:
    ttl-hours: ${REDIS_CART_TTL:2}
  menu:
    ttl-hours: ${REDIS_MENU_TTL:1}

iiko:
  url: https://api-ru.iiko.services
  operation:
    status-check:
      max-attempts: ${IIKO_STATUS_CHECK_MAX_ATTEMPTS:5}
      delay-ms: ${IIKO_STATUS_CHECK_DELAY_MS:500}

digital-waiter:
  url: https://digital-waiter.sberlab.nsu.ru

local:
  url: http://localhost:8081
