server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:db}:${SPRING_DATASOURCE_PORT:5432}/aiwaiter
    username: ${SPRING_DATASOURCE_USERNAME:waiter_user}
    password: ${SPRING_DATASOURCE_PASSWORD:123}

  jpa:
    open-in-view: false

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

  flyway:
    enabled: true
    locations: classpath:db/migration

redis:
  cart:
    ttl-hours: ${REDIS_CART_TTL:2}
  menu:
    ttl-hours: ${REDIS_MENU_TTL:1}

iiko:
  url: https://api-ru.iiko.services
  operation:
    status-check:
      max-attempts: ${IIKO_STATUS_CHECK_MAX_ATTEMPTS:5}
      delay-ms: ${IIKO_STATUS_CHECK_DELAY_MS:500}

digital-waiter:
  url: https://digital-waiter.sberlab.nsu.ru

local:
  url: http://localhost:8081
